language: java
jdk: oraclejdk8


# Define the services to use
services:
  - docker

before_install:
  - sudo service mysql stop
  - docker pull takimatraining/devops-training-db
  - docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db

# Run Unit Test and Integration Tests
script:
  - mvn verify

# Cache the .m2 folder to prevent redownloading dependencies on each build
cache:
  directories:
  - "$HOME/.m2/repository"

env:
  global:
    -secure: "OAK2ggCbeg1XUbOJ7lZ6QNhNEXGiXPHARDjkRk2Lv8qWmIo+wNZ71agWoy7UVOpwGl9UVvqwikoxk+wCJXZRIK1JbhG+VJ7Kv6el2p2Bw6aAWNgq2s1cQ/GJUXurw0ZftECZA+o/Qt7E9Lnwszu6rdfJxtvc8xw3a8nVGGEvxbd6qT3aOgODmEEENTKv67B+bWnvzyStpaNQqxp+9GWqoeF6vjSuV3xKFpJjdN2ZWOSuhDLlpPQBMDgI7ye37UpD+ClVCvxsAh1VhRM4Zx1fixMmnfdSdHP6+itQh7Hsl62tUvshz8BzuG7tmi5RxDsLID6Dm1l7X7EYuZ68sg8kEoYO39vTM5jpnXHrBhqIsOqu4iFJ475dlHKw8sL9nV71vTPdJ++x3C6ecA4jc+Iu25hnlt36Sw2GPT175yJ9O4CanesP95kTMYpZlCDDe9qtnN7bDV7jAGzSbYRqxI/ezqaCDd4/KVt8jJTNmR3n6PWSxz2qYm9z8a4fA5hneXoqEAzjwW1etKEeA6WJFxczKME7/k6TdZkWkJR9v9F7AxXdFvkUauyfAUsOt+QWhyyIl4kAlo+yc9KKNlKPYUeLDQiBLYHO3u0slOqY9U8uuJXr74IuZBBZfQE+4O9iUqcwQUsPhr0tP68VPkwNmFUMk2lJmxR84MAV2QDu6nZ3D5o="


script:
 - |
    mvn clean install sonar:sonar \
    -Dsonar.projectKey=haitamzouhair_sample-application-students \
    -Dsonar.organization=haitamzouhair-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=$SONAR_TOKEN
