language: java
jdk: oraclejdk8


# Define the services to use
services:
  - docker

before_install:
  - sudo service mysql stop
  - docker pull takimatraining/devops-training-db
  - docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db

# Run Unit Test and Integration Tests
script:
  - mvn verify

# Cache the .m2 folder to prevent redownloading dependencies on each build
cache:
  directories:
  - "$HOME/.m2/repository"

env:
  global:
    -secure: "N8BvQMf+erpnrL5vKuKDrzxj9T7TR5e/Ukky/aKnPtMB9GtpeVcDCDDga14t+VjNMSIJrwrR5UkXri+vd5nhKcLe3OYwau5tXUUhCYnxrAZlZdi3qiKhxx9Hy4eh8D8yUp4aMwvvFUM3E9gxW/AR3DI3ezS7U8ECrZb3tGZ0om6fz8XQDpZktVgcrAfx/JFW+1RAObnYiNp2+0htNIzkuygGU5XFC0cMz8X/SvgFGMlRRtB3GzWXZUtw43ZHl5ooooO5mApwdEA6CHxEbEYu8R2DX+AuOMEhPyeGZojX35eGrEDcEhjYvS6F8tUVjAlHsoDrkSo0wOiGujbjT8+7J92kKYJ1Rzyg2ZJ9szm6d9EFKhAayL8g94QtAhwnw3BL4scN/d+AmkZmEII0VuQdjcarTKY15nmBvUyPRVetbCufw07oSSuGJNGcvHz83yp6+o9HePLxtTBRtqMpzQD5vD1xx+Qzw6okzJTGp3dDxGmF4QGlrkn8AlrzZBtNn8oqmLxKON1z7Fakkp0wWfUku/6Um/+nMQUd37ZrNQ1cUd8h/x0IAF3+pbFmhTMIUHOta5GkOIGdD2LYP1+UKTZQWv8FeBkPIgqVziJxzHQzO/IIiyGUactgO5deJJxI+bP442TfW/LvQcev8a+qtJ7dE1rQqClL7fe5Kbg4ax75XEM="


script:
 - |
    mvn clean install sonar:sonar \
    -Dsonar.projectKey=haitamzouhair_sample-application-students \
    -Dsonar.organization=haitamzouhair-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=$SONAR_TOKEN
