language: java
jdk: oraclejdk8


# Define the services to use
services:
  - docker

before_install:
  - sudo service mysql stop
  - docker pull takimatraining/devops-training-db
  - docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db

# Run Unit Test and Integration Tests
script:
  - mvn verify

# Cache the .m2 folder to prevent redownloading dependencies on each build
cache:
  directories:
  - "$HOME/.m2/repository"

env:
  global:
    -secure: "Lk4mIIjUD1U7EKDJvQIoag/0SeCn7xEoWVs2cuu7cWIVwBQKCmFZrJJQSda/MZZealLDB3mZccCEqlApGf3Hw8BQABsmu5gL4WD/tNdc/c+8V19dENLNhKsEO+EYWjzfQ4ojC6q2iggcGLfHDeqaPBadctkoO7Im2ayVa9DvLwRRw/iJADnwzpEoJ9DgnBRcG8m+rzCJf2ZPSHezc+8b94JSoxgxtwvUrVH2Z2K6F2iHHhRb2KPL2ZorUDOw+ONmRNxKixUSlVGrZjpu4d68DJBNoihBG7u5QuT9nI7lvYQoBwfSOJTiTvdeAh6eF4zsQtjrfSXCFH8NZlW/ToCROFqdykT/qKw2hvSfH5MTvkAXFHFgsbDO5StcbfLqAaod9lUOXqlViJCs68anV9++vw9SYIEnkS/uhDJKZJ6EJZpmXFpXoLu+pEiQjoRgr9bgw38PSg9rZKGSKAWze6PE3Hv5Xlx5YdquMewpJ+3RFOUgvCQ4T6hWkWlE7TK71XhrJVZ98ly4AkmtxEnNZUXUltdTbzS7gMrCsbPn1fR4WiwYT9SHBw5ZleurmN4oUvhSltaxqoXOM8j/D2M02AwTRzKOo8pAR935thukNxJ60xhSZOX+CkvxhZKykmQZiZRURde6Yr8TFvMk+Swg4SX8QvopTJgjwilixcaj9whlSVg="


script:
 - |
    mvn clean install sonar:sonar \
    -Dsonar.projectKey=haitamzouhair_sample-application-students \
    -Dsonar.organization=haitamzouhair-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=$SONAR_TOKEN
